spring.datasource.url=jdbc:h2:file:./data/testdb

# Driver / credentials
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Use 'update' to preserve data between builds (only alters schema if entity changes)
# Use 'create' to drop/recreate tables on every startup (for testing)
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Avoid LOB creation issues
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Habilita que ocorra erro quando envia um json com corpo com propriedades inexistentes ou ignoradas
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
