create table item (
    id integer generated by default as identity,
    descricao varchar(100) not null,
    possui_estoque integer not null,
    imagem varchar(255),
    obs varchar(255),
    consumo_direto boolean not null,
    primary key (id)
);

create table receita (
    id integer generated by default as identity,
    descricao varchar(100) not null,
    valor numeric(19, 2) not null,
    imagem varchar(255),
    obs varchar(255),
    primary key (id)
);

create table receita_item (
    fk_receita_id integer not null,
    fk_item_id integer not null,
    primary key (fk_receita_id, fk_item_id),
    constraint FK_RECEITA_ITEM_RECEITA foreign key (fk_receita_id) references receita (id),
    constraint FK_RECEITA_ITEM_ITEM foreign key (fk_item_id) references item (id)
);
